<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

//php artisan db:seed --class=ChecklistSeeder
class ChecklistSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $createdAt = Carbon::now();

      // Inserindo formulário inicial Horta em Casa
      \DB::table('perguntas')->insert(array(
          0 =>
          array(
              'id' => 1,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Dias de visita possíveis',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          1 =>
          array(
              'id' => 2,
              'tipo_pergunta' => 'escolha-simples',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Realiza comercialização?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          2 =>
          array(
              'id' => 3,
              'tipo_pergunta' => 'escolha-simples',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Tem disposição para trabalho em grupo/coletivo?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          3 =>
          array(
              'id' => 4,
              'tipo_pergunta' => 'escolha-simples',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Tem experiência em produção de alimentos?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          4 =>
          array(
              'id' => 5,
              'tipo_pergunta' => 'escolha-simples',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Já possui área produtiva?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          5 =>
          array(
              'id' => 6,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Se sim, qual a produção?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          6 =>
          array(
              'id' => 7,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Qual a disponibilidade de tempo para cuidados com a área?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          7 =>
          array(
              'id' => 8,
              'tipo_pergunta' => 'escolha-simples',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Possui árvores frutíferas?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          8 =>
          array(
              'id' => 9,
              'tipo_pergunta' => 'escolha-simples',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Já houve contato?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          9 =>
          array(
              'id' => 10,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Status de visita',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          10 =>
          array(
              'id' => 11,
              'tipo_pergunta' => 'escolha-simples',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Interesse em seguir no projeto?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          11 =>
          array(
              'id' => 12,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Infraestrutura',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          12 =>
          array(
              'id' => 13,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Ferramentas',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          13 =>
          array(
              'id' => 14,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Mão de obra',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          14 =>
          array(
              'id' => 15,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Demandas gerais',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          15 =>
          array(
              'id' => 16,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'O contato foi realizado como?',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          16 =>
          array(
              'id' => 17,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Água (disponibilidade, origem e qualidade)',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
          17 =>
          array(
              'id' => 18,
              'tipo_pergunta' => 'texto',
              'tabela_colunas' => NULL,
              'tabela_linhas' => NULL,
              'pergunta' => 'Solos (características gerais)',
              'texto_apoio' => NULL,
              'fl_arquivada' => 0,
              'plano_acao_default' => NULL,
              'tags' => 'horta-em-casa',
              'created_at' => $createdAt,
              'updated_at' => $createdAt,
              'deleted_at' => NULL,
          ),
        ));

        \DB::table('respostas')->insert(array(
            0 =>
            array(
                'id' => 1,
                'pergunta_id' => 2,
                'descricao' => 'Sim',
                'cor' => 'verde',
                'texto_apoio' => NULL,
                'ordem' => 1,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            1 =>
            array(
                'id' => 2,
                'pergunta_id' => 2,
                'descricao' => 'Não',
                'cor' => 'vermelho',
                'texto_apoio' => NULL,
                'ordem' => 2,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            2 =>
            array(
                'id' => 3,
                'pergunta_id' => 3,
                'descricao' => 'Sim',
                'cor' => 'verde',
                'texto_apoio' => NULL,
                'ordem' => 1,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            3 =>
            array(
                'id' => 4,
                'pergunta_id' => 3,
                'descricao' => 'Não',
                'cor' => 'vermelho',
                'texto_apoio' => NULL,
                'ordem' => 2,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            4 =>
            array(
                'id' => 5,
                'pergunta_id' => 4,
                'descricao' => 'Sim',
                'cor' => 'verde',
                'texto_apoio' => NULL,
                'ordem' => 1,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            5 =>
            array(
                'id' => 6,
                'pergunta_id' => 4,
                'descricao' => 'Não',
                'cor' => 'vermelho',
                'texto_apoio' => NULL,
                'ordem' => 2,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            6 =>
            array(
                'id' => 7,
                'pergunta_id' => 5,
                'descricao' => 'Sim',
                'cor' => 'verde',
                'texto_apoio' => NULL,
                'ordem' => 1,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            7 =>
            array(
                'id' => 8,
                'pergunta_id' => 5,
                'descricao' => 'Não',
                'cor' => 'vermelho',
                'texto_apoio' => NULL,
                'ordem' => 2,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            8 =>
            array(
                'id' => 9,
                'pergunta_id' => 8,
                'descricao' => 'Sim',
                'cor' => 'verde',
                'texto_apoio' => NULL,
                'ordem' => 1,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            9 =>
            array(
                'id' => 10,
                'pergunta_id' => 8,
                'descricao' => 'Não',
                'cor' => 'vermelho',
                'texto_apoio' => NULL,
                'ordem' => 2,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            10 =>
            array(
                'id' => 11,
                'pergunta_id' => 9,
                'descricao' => 'Sim',
                'cor' => 'verde',
                'texto_apoio' => NULL,
                'ordem' => 1,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            11 =>
            array(
                'id' => 12,
                'pergunta_id' => 9,
                'descricao' => 'Não',
                'cor' => 'vermelho',
                'texto_apoio' => NULL,
                'ordem' => 2,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            12 =>
            array(
                'id' => 13,
                'pergunta_id' => 11,
                'descricao' => 'Sim',
                'cor' => 'verde',
                'texto_apoio' => NULL,
                'ordem' => 1,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
            13 =>
            array(
                'id' => 14,
                'pergunta_id' => 11,
                'descricao' => 'Não',
                'cor' => 'vermelho',
                'texto_apoio' => NULL,
                'ordem' => 2,
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
                'deleted_at' => NULL,
            ),
          ));

          \DB::table('checklists')->insert(array(
              0 =>
              array(
                  'id' => 1,
                  'dominio_id' => 1,
                  'copia_checklist_id' => NULL,
                  'versao' => 0,
                  'nome' => 'Horta em Casa - Formulário Inicial',
                  'instrucoes' => '',
                  'fl_fluxo_aprovacao' => 0,
                  'status' => 'publicado',
                  'plano_acao' => 'nao_criar',
                  'formula' => NULL,
                  'fl_nao_normalizar_percentual' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
          ));

          \DB::table('checklist_categorias')->insert(array(
              0 =>
              array(
                  'id' => 1,
                  'nome' => 'Geral',
                  'ordem' => 1,
                  'checklist_id' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
          ));

          \DB::table('checklist_perguntas')->insert(array(
              0 =>
              array(
                  'id' => 1,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 1,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              1 =>
              array(
                  'id' => 2,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 2,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              2 =>
              array(
                  'id' => 3,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 3,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              3 =>
              array(
                  'id' => 4,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 4,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              4 =>
              array(
                  'id' => 5,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 5,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              5 =>
              array(
                  'id' => 6,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 6,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              6 =>
              array(
                  'id' => 7,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 7,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              7 =>
              array(
                  'id' => 8,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 8,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              8 =>
              array(
                  'id' => 9,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 9,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              9 =>
              array(
                  'id' => 10,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 10,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              10 =>
              array(
                  'id' => 11,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 11,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              11 =>
              array(
                  'id' => 12,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 12,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              12 =>
              array(
                  'id' => 13,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 13,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              13 =>
              array(
                  'id' => 14,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 14,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              14 =>
              array(
                  'id' => 15,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 15,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              15 =>
              array(
                  'id' => 16,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 16,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              16 =>
              array(
                  'id' => 17,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 17,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              17 =>
              array(
                  'id' => 18,
                  'checklist_categoria_id' => 1,
                  'pergunta_id' => 18,
                  'peso_pergunta' => NULL,
                  'fl_obrigatorio' => 0,
                  'fl_plano_acao' => 0,
                  'plano_acao_prioridade' => NULL,
                  'ordem' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
          ));


          \DB::table('checklist_unidade_operacionais')->insert(array(
              0 =>
              array(
                  'id' => 1,
                  'checklist_id' => 1,
                  'unidade_operacional_id' => 1,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              1 =>
              array(
                  'id' => 2,
                  'checklist_id' => 1,
                  'unidade_operacional_id' => 2,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              2 =>
              array(
                  'id' => 3,
                  'checklist_id' => 1,
                  'unidade_operacional_id' => 3,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
              3 =>
              array(
                  'id' => 4,
                  'checklist_id' => 1,
                  'unidade_operacional_id' => 4,
                  'created_at' => $createdAt,
                  'updated_at' => $createdAt,
                  'deleted_at' => NULL,
              ),
          ));
      }
}
